# -*- coding: utf-8 -*-

CRIME_DICT = {
    "ASSAULT": ["ASSAULT"],
    "THEFT": [
        "BIKE THEFT", "BURGLARY", "CAR PROWL", "MAIL THEFT", "PICKPOCKET",
        "PURSE SNATCH", "SHOPLIFTING", "THEFT OF SERVICES", "VEHICLE THEFT",
        "BURGLARY-SECURE PARKING-RES"
    ],
    "SIN": ["GAMBLE", "PORNOGRAPHY", "PROSTITUTION"],
    "DRUGS": [
        "DUI", "LIQUOR VIOLATION", "NARCOTICS", "STAY OUT OF AREA OF DRUGS"
    ],
    "FRAUD": ["COUNTERFEIT", "EMBEZZLE", "FORGERY", "FRAUD"],
    "HOMICIDE": ["HOMICIDE"],
    "PROPERTY": [
        "ILLEGAL DUMPING", "LOST PROPERTY", "OTHER PROPERTY",
        "PROPERTY DAMAGE", "RECKLESS BURNING", "RECOVERED PROPERTY",
        "STOLEN PROPERTY",
    ],
    "ROBBERY": ["ROBBERY"],
    "WEAPON": ["WEAPON"],
    "DISTURBANCE": [
        "DISORDERLY CONDUCT", "DISPUTE", "FIREWORK", "PUBLIC NUISANCE",
        "THREATS", "TRESPASS", "DISTURBANCE", "THREATS"
    ],
    "OTHER": [
        "ANIMAL COMPLAINT", "BIAS INCIDENT", "ELUDING", "ESCAPE", "EXTORTION",
        "HARBOR CALLS", "INJURY", "LOITERING", "METRO", "OBSTRUCT", "TRAFFIC",
        "WARRANT ARREST", "VIOLATION OF COURT ORDER",
        "[INC - CASE DC USE ONLY]", "FALSE REPORT",
    ],
}
